import Head from 'next/head';
import { useColorModeValue } from '@chakra-ui/react';
import styles from '../styles/Home.module.css';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Main from '../components/Main';

export default function Home() {
  const bgColor = useColorModeValue('beige', null);
  return (
    <div className={styles.container} style={{ backgroundColor: bgColor }}>
      <Head>
        <title>Probability Simulator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Main />
      <Footer />
    </div>
  );
};
